INSERT INTO API_record (title,artist,"year",genre,deezer_id,price,available_units)
VALUES ('Joyride',
        'Roxette',
        1991,
        'Pop / Rock',
        '138128662',
        0,
        0), ('Crash! Boom! Bang!',
             'Roxette',
             1994,
             'Pop / Rock',
             '137971192',
             0,
             0), ('Look Sharp!',
                  'Roxette',
                  1988,
                  'Pop / Rock',
                  '138111272',
                  0,
                  0), ('Have A Nice day',
                       'Roxette',
                       1999,
                       'Pop / Rock',
                       '138093562',
                       0,
                       0), ('A Night At The Opera',
                            'Queen',
                            1975,
                            'Rock',
                            '915785',
                            0,
                            0), ('A Day At The Races',
                                 'Queen',
                                 1976,
                                 'Rock',
                                 '917232',
                                 0,
                                 0), ('News Of The World',
                                      'Queen',
                                      1977,
                                      'Rock',
                                      '1121181',
                                      0,
                                      0), ('A Kind Of Magic',
                                           'Queen',
                                           1986,
                                           'Rock',
                                           '1232876',
                                           0,
                                           0), ('Bon Jovi',
                                                'Bon Jovi',
                                                1984,
                                                'Rock',
                                                '7373433',
                                                0,
                                                0), ('Cross Road',
                                                     'Bon Jovi',
                                                     1994,
                                                     'Rock',
                                                     '70189822',
                                                     0,
                                                     0);


INSERT INTO API_record (title,artist,"year",genre,deezer_id,price,available_units)
VALUES ('These Days',
        'Bon Jovi',
        1995,
        'Rock',
        '2378481',
        0,
        0), ('Have A Nice Day',
             'Bon Jovi',
             2005,
             'Rock',
             '5942159',
             0,
             0), ('Come Away With Me',
                  'Norah Jones',
                  2002,
                  'Jazz',
                  '318674457',
                  0,
                  0), ('Foreverly',
                       'Norah Jones',
                       2013,
                       'Blues',
                       '7116008',
                       0,
                       0), ('Feels Like Home',
                            'Norah Jones',
                            2004,
                            'Pop',
                            '100448152',
                            0,
                            0), ('The Look Of Love',
                                 'Diana Krall',
                                 2001,
                                 'Jazz',
                                 '117807',
                                 0,
                                 0), ('Turn Up The Quiet',
                                      'Diana Krall',
                                      2017,
                                      'Jazz',
                                      '40798221',
                                      0,
                                      0), ('Random Access Memories',
                                           'Daft Punk',
                                           2013,
                                           'Techno',
                                           '6575789',
                                           0,
                                           0), ('Homework',
                                                'Daft Punk',
                                                1997,
                                                'Techno',
                                                '301775',
                                                0,
                                                0);

